SINGULARITY_LOCALCACHEDIR=/scratch/llecca

SINGULARITY_CACHEDIR=/scratch/llecca

SINGULARITY_TMPDIR=/scratch/llecca

export SINGULARITY_LOCALCACHEDIR
export SINGULARITY_CACHEDIR
export SINGULARITY_TMPDIR
